apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: disable-powerkey
  name: disable-powerkey
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: disable-powerkey
  template:
    metadata:
      labels:
        app: disable-powerkey
    spec:
      tolerations:
      # Run regardless of any existing taints.
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      affinity:
        nodeAffinity:
         # Restrict to preemptible nodes
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: Exists
      containers:
      - env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            set -o errexit
            set -o pipefail
            set -o nounset
            sed -i -e "s/#HandlePowerKey=poweroff/HandlePowerKey=ignore/g" /etc/systemd/logind.conf
            systemctl restart systemd-logind
        image: gcr.io/google-containers/startup-script:v1
        imagePullPolicy: Always
        name: disable-powerkey
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 10m
      hostPID: true
  updateStrategy:
    type: OnDelete

