apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
  labels:
    app: nginx
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 3
  minReadySeconds: 60
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "80"
      labels:
        app: nginx
    spec:
      tolerations:
      - key: "for"
        operator: "Equal"
        value: "preemptible"
        effect: "NoSchedule"
      nodeSelector:
        for: preemptible
      volumes:
      - name: confd-volume
        configMap:
          name: nginxconfd
      - name: conf-volume
        configMap:
          name: nginxconf
      containers:
      - name: nginxhttp
        image: firesh/nginx-lua
        command: ["sh", "-c"]
        args: ["touch /usr/share/nginx/html/readiness; nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command:
                - sh
                - -c
                - |
                  rm /usr/share/nginx/html/readiness;
                  sleep 25;
                  /usr/sbin/nginx -s quit;
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 60
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 2
          timeoutSeconds: 2
          failureThreshold: 2
          successThreshold: 2
        resources:
          requests:
            cpu: 500m
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: confd-volume
        - mountPath: /etc/nginx
          name: conf-volume
      terminationGracePeriodSeconds: 30
